# Generated by Django 4.0.4 on 2022-05-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_creations', models.DateTimeField(auto_now_add=True, verbose_name='time of creations')),
                ('question', models.CharField(max_length=100, verbose_name='question')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'poll',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_creations', models.DateTimeField(auto_now_add=True, verbose_name='time of creations')),
                ('variant_text', models.CharField(max_length=100, verbose_name='variant text')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.poll', verbose_name='Choice')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'db_table': 'choice',
            },
        ),
    ]
