# Generated by Django 4.0.4 on 2022-05-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='variant_text',
            field=models.CharField(max_length=100, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
    ]
